define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Info generated by Appery.io
         * @module Info
         */
        APP.controller('InfoController', ['$scope', 'Apperyio', InfoController]);

        function InfoController($scope, Apperyio) {
            // user controller variables
            // user controller functions
        }
    });