define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Buyer_Ins generated by Appery.io
         * @module Buyer_Ins
         */
        APP.controller('Buyer_Ins', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
            };
            /**
             * @function gotoVerify
             */
            $scope.gotoVerify = function() {
                Apperyio.navigateTo("tab_Verify", {
                    'reloadPage': true
                });
            };
        }
    });