define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Modal_Buyer_Accept_Offer generated by Appery.io
         * @module Modal_Buyer_Accept_Offer
         */
        APP.controller('Modal_Buyer_Accept_OfferController', ['$scope', 'Apperyio', Modal_Buyer_Accept_OfferController]);

        function Modal_Buyer_Accept_OfferController($scope, Apperyio) {
            // user controller variables
            $scope.RequestModel = Apperyio.EntityAPI('String');
            // user controller functions
        }
    });