define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Screen1 generated by Appery.io
         * @module Screen1
         */
        APP.controller('Screen1', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.devID = Apperyio.EntityAPI('String');
            $scope.timeZone = Apperyio.EntityAPI('String');
            $scope.shift = Apperyio.EntityAPI('String');
            $scope.message = Apperyio.EntityAPI('String');
            $scope.channel = Apperyio.EntityAPI('String');
            $scope.object_id = Apperyio.EntityAPI('String');
            $scope.username1 = Apperyio.EntityAPI('String');
            $scope.devID1 = Apperyio.EntityAPI('String');
            $scope.main = Apperyio.EntityAPI('Main');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                //document.addEventListener("push-notification", function(event) {alert(event.detail.message);});
                //$scope.regPush();
                $scope.timeZone = "GMT-04:00";
                document.addEventListener("push-notification", function(event) {
                    alert(event.detail.message);
                });
                $scope.regPush();
                //This part below gets the user name
                var main = {};
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username1 = AllData.username;
                main.username1 = username1;
                $scope.main.username1 = username1;
                //$scope.main.object_id1 = "poo";
                //Get User  
                console.log("main.username1:", main.username1);
                console.log("username1:", username1);
                console.log("AllData:", AllData);
            };
            /**
             * @function regPush
             */
            $scope.regPush = function() {
                //This part below registers phone
                var requestData = {};
                /*|button_mapping|onbeforesend|838C0496-7B6A-94CB-C133-467D83DC8CC7||2560|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("PushRegisterDevice")(requestData).then(
                    /*|service_bookmark|bookmark|838C0496-7B6A-94CB-C133-467D83DC8CC7||6346|*/
                    function(success) { // success callback
                        (function mapping7833(success, $scope) {
                            var main_scope = $scope.main;
                            _.set(main_scope, 'object_id1', success._id);
                            _.set(main_scope, 'devID1', success.deviceID);
                            $scope.main = main_scope;
                            alert("Success. \n" + "Device ID: " + $scope.main.devID1 + "ObjectID:" + $scope.main.object_id1);
                            /*|button_mapping|onsuccess|838C0496-7B6A-94CB-C133-467D83DC8CC7||7833|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        alert("ERROR:\n" + JSON.stringify(error));
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                devID1 = $scope.devID;
                $scope.devID1 = devID1
            };
            /**
             * @function sendPush
             */
            $scope.sendPush = function() {
                $scope.message = prompt("Enter your push text: ", "Test push");
                var requestData = {};
                requestData = (function mapping1884($scope) {
                    var requestData = {};
                    requestData.data = Apperyio.EntityAPI('PushSend.request.body', undefined, true);
                    console.log(requestData.data)
                    var mess_scope = $scope.mess;
                    requestData.data.payload.message = mess_scope;
                    return requestData;
                    /*|button_mapping|onbeforesend|0E74CFC2-73EE-DF0B-A3B5-D1F4C1B3FDED||1884|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("PushSend")(requestData).then(
                    /*|service_bookmark|bookmark|0E74CFC2-73EE-DF0B-A3B5-D1F4C1B3FDED||6816|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|0E74CFC2-73EE-DF0B-A3B5-D1F4C1B3FDED||4381|*/
                    },
                    function(error) { // callback to handle request error
                        alert("ERROR:n" + JSON.stringify(error));
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function displayData
             */
            $scope.displayData = function() {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.main.object_id = data;
                alert("Second Alert:" + "ObjectID: " + $scope.main.object_id1 + " / " + $scope.main.username1);
                console.log($scope.main.object_id1);
                var requestData = {};
                requestData = (function mapping2861($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var main_scope = $scope.main;
                    requestData.params.Device_id = main_scope.object_id1;
                    requestData.params.user = main_scope.username1;
                    return requestData;
                    /*|button_mapping|onbeforesend|9B861516-F037-900D-2DA6-E96E04CFEF78||2861|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("Insert_User_Device_service")(requestData).then(
                    /*|service_bookmark|bookmark|9B861516-F037-900D-2DA6-E96E04CFEF78||5224|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|9B861516-F037-900D-2DA6-E96E04CFEF78||3145|*/
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
        }
    });