define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Buyer_Request_Test generated by Appery.io
         * @module Buyer_Request_Test
         */
        APP.controller('Buyer_Request_Test', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.user = Apperyio.EntityAPI('User');
            $scope.RequestModel = Apperyio.EntityAPI('String');
            $scope.RequestMem = Apperyio.EntityAPI('String');
            $scope.RequestColor = Apperyio.EntityAPI('String');
            $scope.RequestQuan = Apperyio.EntityAPI('String');
            $scope.customList = Apperyio.EntityAPI('Array');
            $scope.selected = Apperyio.EntityAPI('Wrapper');
            $scope.list = Apperyio.EntityAPI('List');
            $scope.selected1 = Apperyio.EntityAPI('Wrapper1');
            $scope.list1 = Apperyio.EntityAPI('List1');
            $scope.selected2 = Apperyio.EntityAPI('Wrapper2');
            $scope.list2 = Apperyio.EntityAPI('List2');
            $scope.RequestManu = Apperyio.EntityAPI('String');
            $scope.RequestExpiration = Apperyio.EntityAPI('String');
            $scope.buyer = Apperyio.EntityAPI('String');
            $scope.RequestCondition = Apperyio.EntityAPI('String');
            $scope.testinput = Apperyio.EntityAPI('String');
            $scope.RequestNotes = Apperyio.EntityAPI('String');
            $scope.RequestShipping = Apperyio.EntityAPI('String');
            $scope.selected3 = Apperyio.EntityAPI('Wrapper3');
            $scope.list3 = Apperyio.EntityAPI('List3');
            $scope.token = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var requestData = {};
                /*|button_mapping|onbeforesend|6A71953F-CA43-34BC-C5E5-604C42CE6608||6767|*/
                // Get Company Select from database
                Apperyio.get("menu_Main_Company_service")(requestData).then(
                    /*|service_bookmark|bookmark|6A71953F-CA43-34BC-C5E5-604C42CE6608||4946|*/
                    function(success) { // success callback
                        (function mapping3905(success, $scope) {
                            var list_scope = $scope.list;
                            var selected_scope = $scope.selected;
                            list_scope = success.data;
                            _.set(selected_scope, 'item', success.data[0]);
                            $scope.list = list_scope;
                            $scope.selected = selected_scope;
                            //$scope.RequestManu = ($scope.selected.item);
                            Request.RequestManu = ($scope.selected.item);
                            /*|button_mapping|onsuccess|6A71953F-CA43-34BC-C5E5-604C42CE6608||3905|*/
                        })(success, $scope);
                        console.log("Manu:", Request.RequestManu);
                        //var RequestManu = $scope.selected.item;
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                console.log("Manu1:", Request.RequestManu);
                // $scope.$watch('$scope.selected.item', function () {
                var requestData = {};
                requestData = (function mapping4836($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var RequestManu_scope = $scope.RequestManu;
                    requestData.params.Company = RequestManu_scope;
                    return requestData;
                    /*|button_mapping|onbeforesend|F7BFF7DE-7446-7D33-0660-2867C785A50D||4836|*/
                })($scope);
                // Get Memory Select from database
                //console.log("RequestManu:",RequestManu);
                Apperyio.get("menu_Main_Type_service")(requestData).then(
                    /*|service_bookmark|bookmark|F7BFF7DE-7446-7D33-0660-2867C785A50D||7376|*/
                    function(success) { // success callback
                        (function mapping5771(success, $scope) {
                            var list1_scope = $scope.list1;
                            var selected1_scope = $scope.selected1;
                            list1_scope = success.data;
                            _.set(selected1_scope, 'item1', success.data[0]);
                            $scope.list1 = list1_scope;
                            $scope.selected1 = selected1_scope;
                            /*|button_mapping|onsuccess|F7BFF7DE-7446-7D33-0660-2867C785A50D||5771|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                /*|button_mapping|onbeforesend|6C22ABF9-C1B5-B8D8-58B0-0AF9B1B015C3||8458|*/
                // Get Color Select from database
                Apperyio.get("phoneapp_Color_list_service")(requestData).then(
                    /*|service_bookmark|bookmark|6C22ABF9-C1B5-B8D8-58B0-0AF9B1B015C3||5835|*/
                    function(success) { // success callback
                        (function mapping2854(success, $scope) {
                            var list2_scope = $scope.list2;
                            var selected2_scope = $scope.selected2;
                            list2_scope = success.data;
                            _.set(selected2_scope, 'item2', success.data[0]);
                            $scope.list2 = list2_scope;
                            $scope.selected2 = selected2_scope;
                            /*|button_mapping|onsuccess|6C22ABF9-C1B5-B8D8-58B0-0AF9B1B015C3||2854|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                /*|button_mapping|onbeforesend|4164BE69-8420-13B6-6D43-76BC0496424F||3768|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("phoneapp_ShippingMethod_list_service")(requestData).then(
                    /*|service_bookmark|bookmark|4164BE69-8420-13B6-6D43-76BC0496424F||8483|*/
                    function(success) { // success callback
                        (function mapping7797(success, $scope) {
                            var list3_scope = $scope.list3;
                            var selected3_scope = $scope.selected3;
                            list3_scope = success.data;
                            _.set(selected3_scope, 'item3', success.data[0]);
                            $scope.list3 = list3_scope;
                            $scope.selected3 = selected3_scope;
                            /*|button_mapping|onsuccess|4164BE69-8420-13B6-6D43-76BC0496424F||7797|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function addItem
             */
            $scope.addItem = function() {
                RequestModel = ($scope.selected.item);
                RequestMem = ($scope.selected1.item1.mem);
                RequestColor = ($scope.selected2.item2.Color);
                RequestShipping = ($scope.selected3.item3.ShippingType);
                RequestCondition = ($scope.condition);
                RequestQuan = ($scope.quantity);
                RequestExpiration = ($scope.expiration);
                RequestManu = ($scope.selected.item.Manu);
                RequestModel = ($scope.selected.item.name);
                RequestNotes = ($scope.notes);
                RequestKitted = ($scope.Kitted);
                RequestCarrier = ($scope.Carrier);
                //Get User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var buyer = AllData.username;
                var session = AllData.session
                var bMail = AllData.email
                var bCell = AllData.MobilePhone
                var token = AllData.session;
                //Get User     
                //Debug    
                console.log(RequestManu, $scope.selected.item.Manu);
                console.log(RequestModel, $scope.selected.item.name);
                console.log(RequestMem, $scope.selected1.item1.mem);
                console.log(RequestColor);
                console.log(RequestCondition);
                console.log(RequestQuan);
                console.log(RequestExpiration);
                console.log(buyer);
                console.log($scope.selected.item.Manu);
                console.log($scope.selected.item.name);
                console.log($scope.selected1.item1.mem);
                console.log($scope.selected3.item3.ShippingType);
                console.log(RequestCarrier);
                console.log(bMail);
                console.log(bCell);
                var requestData = {};
                requestData = (function mapping8363($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var buyer_scope = $scope.buyer;
                    var bMail_scope = $scope.bMail;
                    var bCell_scope = $scope.bCell;
                    var RequestMem_scope = $scope.RequestMem;
                    var RequestModel_scope = $scope.RequestModel;
                    var RequestColor_scope = $scope.RequestColor;
                    var RequestCondition_scope = $scope.RequestCondition;
                    var RequestQuan_scope = $scope.RequestQuan;
                    var RequestExpiration_scope = $scope.RequestExpiration;
                    var RequestManu_scope = $scope.RequestManu;
                    var RequestShip_scope = $scope.RequestShipping;
                    requestData.params.Buyer_username = buyer;
                    requestData.params.Memory = RequestMem;
                    requestData.params.Product = RequestModel;
                    requestData.params.Color = RequestColor;
                    requestData.params.Condition = RequestCondition;
                    requestData.params.Quantity = RequestQuan;
                    requestData.params.Expiration = RequestExpiration;
                    requestData.params.manufacturer = RequestManu;
                    requestData.params.RNotes = RequestNotes;
                    requestData.params.Shipping = RequestShipping;
                    requestData.params.Kitted = RequestKitted;
                    requestData.params.Carrier = RequestCarrier;
                    requestData.params.B_Requests1 = bMail;
                    requestData.params.B_Requests2 = bCell;
                    requestData.headers = {};
                    var token_scope = $scope.token;
                    requestData.headers['X-Appery-Session-Token'] = token;
                    console.log("token", token);
                    return requestData;
                    /*|button_mapping|onbeforesend|1A38ED9E-9DCE-6838-29D0-683E5615E260||8363|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("InsertRequest_service")(requestData).then(
                    /*|service_bookmark|bookmark|1A38ED9E-9DCE-6838-29D0-683E5615E260||3932|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|1A38ED9E-9DCE-6838-29D0-683E5615E260||1983|*/
                        var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                            animation: 'slide-in-up', // The animation to show & hide with
                            focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                            backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                            hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                        };
                        Apperyio.get('Modals').loadModal("Modal_Buyer_Request").then(
                            function(modalInstance) {
                                modalInstance.open(modalOptions).then(function(modal) {
                                    modal.scope.modal = modal;
                                    modal.scope.result = "You have requested the following:";
                                    modal.scope.result1 = RequestManu;
                                    modal.scope.result2 = RequestModel;
                                    modal.scope.result3 = RequestMem;
                                    modal.scope.result4 = RequestColor;
                                    modal.scope.result5 = RequestKitted;
                                    modal.scope.result6 = RequestQuan;
                                    modal.scope.result7 = RequestExpiration;
                                    modal.scope.result8 = RequestShipping;
                                    modal.scope.result9 = RequestCarrier;
                                    modal.show();
                                });
                            },
                            function(error) {
                                var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                                    animation: 'slide-in-up', // The animation to show & hide with
                                    focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                                    backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                                };
                                Apperyio.get('Modals').loadModal("Info").then(
                                    function(modalInstance) {
                                        modalInstance.open(modalOptions).then(function(modal) {
                                            modal.scope.modal = modal;
                                            modal.scope.result = "Please Try Again. There was an error";
                                            modal.show();
                                        });
                                    },
                                    function(error) {
                                        console.log(error);
                                    });
                                console.log(error);
                            });
                    },
                    function(error) { // callback to handle request error
                        Apperyio.navigateTo("Login", {});
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                Apperyio.navigateTo("Buyer_Home", {});
            };
        }
    });