define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Buyer_Accept_Offer generated by Appery.io
         * @module Buyer_Accept_Offer
         */
        APP.controller('Buyer_Accept_Offer', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.RequestID2 = Apperyio.EntityAPI('DataStorage');
            $scope.RequestID3 = Apperyio.EntityAPI('String');
            $scope.Buyer_username1 = Apperyio.EntityAPI('String');
            $scope.manufacturer1 = Apperyio.EntityAPI('String');
            $scope.Product1 = Apperyio.EntityAPI('String');
            $scope.Memory1 = Apperyio.EntityAPI('String');
            $scope.Color1 = Apperyio.EntityAPI('String');
            $scope.Condition1 = Apperyio.EntityAPI('String');
            $scope.Quantity1 = Apperyio.EntityAPI('Number');
            $scope.B_Requests1A = Apperyio.EntityAPI('String');
            $scope.B_Requests2A = Apperyio.EntityAPI('String');
            $scope.B_Requests3A = Apperyio.EntityAPI('String');
            $scope.B_Requests4A = Apperyio.EntityAPI('String');
            $scope.B_Requests5A = Apperyio.EntityAPI('String');
            $scope.RNotes1 = Apperyio.EntityAPI('String');
            $scope._createdAt1 = Apperyio.EntityAPI('String');
            $scope.RequestID4 = Apperyio.EntityAPI('String');
            $scope.miniID = Apperyio.EntityAPI('String');
            $scope.Seller_username = Apperyio.EntityAPI('String');
            $scope.OfferNotes1 = Apperyio.EntityAPI('String');
            $scope.BuyerPrice1 = Apperyio.EntityAPI('String');
            $scope.offerExpires1 = Apperyio.EntityAPI('String');
            $scope.Shipping1 = Apperyio.EntityAPI('String');
            $scope.Seller1 = Apperyio.EntityAPI('String');
            $scope.RequestNotes2 = Apperyio.EntityAPI('String');
            $scope.Kitted1 = Apperyio.EntityAPI('String');
            $scope.Carrier1 = Apperyio.EntityAPI('String');
            $scope.S_Offers1A = Apperyio.EntityAPI('String');
            $scope.S_Offers2A = Apperyio.EntityAPI('String');
            $scope.S_Offers3A = Apperyio.EntityAPI('String');
            $scope.S_Offers4A = Apperyio.EntityAPI('String');
            $scope.S_Offers5A = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var RequestID3 = ""
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID2.Gl_Vars = data;
                console.log($scope.RequestID2.Gl_Vars.request_id);
                RequestID3 = $scope.RequestID2.Gl_Vars.request_id;
                console.log("RequestID3= ", RequestID3);
                var miniID = "";
                // Get Data from Request
                var requestData = {};
                requestData = (function mapping5835($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var RequestID3_scope = $scope.RequestID3;
                    requestData.params.CurrentRequestID = RequestID3;
                    return requestData;
                    /*|button_mapping|onbeforesend|F72C58AD-0CB1-F18F-161F-44E1632C9FEA||5835|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("Request_ToBuyer_offer_Detail_service")(requestData).then(
                    /*|service_bookmark|bookmark|F72C58AD-0CB1-F18F-161F-44E1632C9FEA||4091|*/
                    function(success) { // success callback
                        (function mapping7623(success, $scope) {
                            var Product1_scope = $scope.Product1;
                            var _id_scope = $scope._id1;
                            var fk_Request_id1_scope = $scope.fk_Request_id1;
                            var Condition1_scope = $scope.Condition1;
                            var manufacturer1_scope = $scope.manufacturer1;
                            var RNotes1_scope = $scope.RNotes1;
                            var Quantity1_scope = $scope.Quantity1;
                            var Memory1_scope = $scope.Memory1;
                            var Color1_scope = $scope.Color1;
                            var Shipping1_scope = $scope.Shipping1;
                            var OfferNotes1_scope = $scope.OfferNotes1;
                            var BuyerPrice1_scope = $scope.BuyerPrice1;
                            var offerExpires1_scope = $scope.offerExpires1;
                            var Carrier1_scope = $scope.Carrier1;
                            var Kitted1_scope = $scope.Kitted1;
                            var S_Offers1A_scope = $scope.S_Offers1A;
                            var S_Offers2A_scope = $scope.S_Offers2A;
                            var B_Requests1A_scope = $scope.B_Requests1A;
                            var B_Requests2A_scope = $scope.B_Requests2A;
                            //The following are not show in the grid - They are for Acceptance
                            var Seller1_scope = $scope.Seller1;
                            var OfferPrice1_scope = $scope.OfferPrice1;
                            var SellerPrice1_scope = $scope.SellerPrice1;
                            //Get Values From SellerOffers Collection
                            Product1_scope = success.data[0].so_Product;
                            _id1_scope = success.data[0]._id;
                            fk_Request_id1_scope = success.data[0].fk_Request_id;
                            Condition1_scope = success.data[0].so_Condition;
                            manufacturer1_scope = success.data[0].so_manufacturer;
                            RNotes1_scope = success.data[0].so_RNotes;
                            Quantity1_scope = success.data[0].so_Quantity;
                            Memory1_scope = success.data[0].so_Memory;
                            Color1_scope = success.data[0].so_Color;
                            Shipping1_scope = success.data[0].so_Shipping;
                            OfferNotes1_scope = success.data[0].OfferNotes;
                            BuyerPrice1_scope = success.data[0].BuyerPrice;
                            offerExpires1_scope = success.data[0].OfferExpirationDate.$date;
                            Seller1_scope = success.data[0].Seller_username;
                            OfferPrice1_scope = success.data[0].OfferPrice;
                            SellerPrice1_scope = success.data[0].SellerPrice;
                            Kitted1_scope = success.data[0].so_Kitted;
                            Carrier1_scope = success.data[0].so_Carrier;
                            B_Requests1A_scope = success.data[0].so_B_Requests1;
                            B_Requests2A_scope = success.data[0].so_B_Requests2;
                            S_Offers1A_scope = success.data[0].S_Offers1;
                            S_Offers2A_scope = success.data[0].S_Offers2;
                            //Put it
                            $scope.Product1 = Product1_scope;
                            $scope._id1 = _id1_scope;
                            $scope.fk_Request_id1 = fk_Request_id1_scope;
                            $scope.Condition1 = Condition1_scope;
                            $scope.manufacturer1 = manufacturer1_scope;
                            $scope.RNotes1 = RNotes1_scope;
                            $scope.Quantity1 = Quantity1_scope;
                            $scope.Memory1 = Memory1_scope;
                            $scope.Color1 = Color1_scope;
                            $scope.Shipping1 = Shipping1_scope;
                            $scope.OfferNotes1 = OfferNotes1_scope;
                            $scope.BuyerPrice1 = BuyerPrice1_scope;
                            $scope.offerExpires1 = offerExpires1_scope;
                            $scope.Seller1 = Seller1_scope;
                            $scope.OfferPrice1 = OfferPrice1_scope;
                            $scope.SellerPrice1 = SellerPrice1_scope;
                            $scope.Kitted1 = Kitted1_scope;
                            $scope.Carrier1 = Carrier1_scope;
                            $scope.B_Requests1A = B_Requests1A_scope;
                            $scope.B_Requests2A = B_Requests2A_scope;
                            $scope.S_Offers1A = S_Offers1A_scope;
                            $scope.S_Offers2A = S_Offers2A_scope;
                            /*|button_mapping|onsuccess|F72C58AD-0CB1-F18F-161F-44E1632C9FEA||7623|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function gotoPage
             */
            $scope.gotoPage = function() {
                Apperyio.navigateTo("Buyer_Home", {});
            };
            /**
             * @function PlaceOffer
             */
            $scope.PlaceOffer = function() {
                //On load screen logic
                var requestData = {};
                //Get Seller User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var Seller_username = AllData.username;
                //Get User  
                console.log(username);
                var requestData = {};
                requestData = (function mapping3480($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var Seller_username_scope = $scope.Seller_username;
                    var RequestID4_scope = $scope.RequestID4;
                    var RNotes1_scope = $scope.RNotes1;
                    var B_Requests5A_scope = $scope.B_Requests5A;
                    var B_Requests4A_scope = $scope.B_Requests4A;
                    var B_Requests3A_scope = $scope.B_Requests3A;
                    var B_Requests2A_scope = $scope.B_Requests2A;
                    var B_Requests1A_scope = $scope.B_Requests1A;
                    var Quantity1_scope = $scope.Quantity1;
                    var Condition1_scope = $scope.Condition1;
                    var Color1_scope = $scope.Color1;
                    var Memory1_scope = $scope.Memory1;
                    var Product1_scope = $scope.Product1;
                    var manufacturer1_scope = $scope.manufacturer1;
                    var Buyer_username1_scope = $scope.Buyer_username1;
                    var OfferNotes = ($scope.SellerNotes);
                    var OfferPrice = ($scope.BidAmount);
                    requestData.params.Seller_username = Seller_username_scope;
                    requestData.params.RequestID4 = RequestID4_scope;
                    requestData.params.RNotes = RNotes1_scope;
                    requestData.params.B_Requests5 = B_Requests5A_scope;
                    requestData.params.B_Requests4 = B_Requests4A_scope;
                    requestData.params.B_Requests3 = B_Requests3A_scope;
                    requestData.params.B_Requests2 = B_Requests2A_scope;
                    requestData.params.B_Requests1 = B_Requests1A_scope;
                    requestData.params.Quantity = Quantity1_scope;
                    requestData.params.Condition = Condition1_scope;
                    requestData.params.Color = Color1_scope;
                    requestData.params.Memory = Memory1_scope;
                    requestData.params.Product = Product1_scope;
                    requestData.params.manufacturer = manufacturer1_scope;
                    requestData.params.Buyer_username = Buyer_username1_scope;
                    requestData.params.Seller_username = Seller_username;
                    requestData.params.OfferNotes = OfferNotes;
                    requestData.params.OfferPrice = OfferPrice;
                    return requestData;
                    /*|button_mapping|onbeforesend|061FD875-61E6-1D52-3B68-23238C2E995D||3480|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("InsertOffers_service")(requestData).then(
                    /*|service_bookmark|bookmark|061FD875-61E6-1D52-3B68-23238C2E995D||9919|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|061FD875-61E6-1D52-3B68-23238C2E995D||2123|*/
                        var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                            animation: 'slide-in-up', // The animation to show & hide with
                            focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                            backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                            hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                        };
                        Apperyio.get('Modals').loadModal("Modal_Seller_Accept").then(
                            function(modalInstance) {
                                modalInstance.open(modalOptions).then(function(modal) {
                                    modal.scope.modal = modal;
                                    modal.scope.result = "You have offered the following:";
                                    modal.scope.result1 = $scope.manufacturer1;
                                    modal.scope.result2 = $scope.Product1;
                                    modal.scope.result3 = $scope.Memory1;
                                    modal.scope.result4 = $scope.Color1;
                                    modal.scope.result5 = $scope.Condition1;
                                    modal.scope.result6 = $scope.Quantity1;
                                    modal.scope.result7 = $scope.BidAmount;
                                    modal.show();
                                });
                            },
                            function(error) {
                                console.log(error);
                            });
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                Apperyio.navigateTo("Seller_Home", {});
            };
            /**
             * @function RejectOffer
             */
            $scope.RejectOffer = function() {
                var requestData = {};
                requestData = (function mapping6941($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var RequestID2_scope = $scope.RequestID2;
                    requestData.params.CurrentRequestID = RequestID2_scope.Gl_Vars.request_id;
                    return requestData;
                    /*|button_mapping|onbeforesend|411E9C43-4BDD-FED0-6DF8-95B0552070DE||6941|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("BuyerRejectOffer_service")(requestData).then(
                    /*|service_bookmark|bookmark|411E9C43-4BDD-FED0-6DF8-95B0552070DE||5921|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|411E9C43-4BDD-FED0-6DF8-95B0552070DE||8259|*/
                        var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                            animation: 'slide-in-up', // The animation to show & hide with
                            focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                            backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                            hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                        };
                        Apperyio.get('Modals').loadModal("Info").then(
                            function(modalInstance) {
                                modalInstance.open(modalOptions).then(function(modal) {
                                    modal.scope.modal = modal;
                                    modal.scope.result = "You Have Successfully Rejected the Offer";
                                    modal.show();
                                });
                            },
                            function(error) {
                                console.log(error);
                            });
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                Apperyio.navigateTo("Buyer_Home", {});
            };
            /**
             * @function AcceptOffer
             */
            $scope.AcceptOffer = function() {
                //On load screen logic
                var requestData = {};
                //Get Seller User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                //Get User  Info
                var Buyer = AllData.username;
                var CompanyName = AllData.Company;
                var ShipFirstName = AllData.FirstName;
                var ShipLastName = AllData.LastName;
                var ShipAddress1 = AllData.ShippingAddress1;
                var ShipAddress2 = AllData.ShippingAddress2;
                var ShipCity = AllData.City;
                var ShipState = AllData.State;
                var ShipZip = AllData.Zip;
                var Country = AllData.country;
                var ShipPhone = AllData.BusinessPhone;
                var ResaleNumber = AllData.ResaleNumber;
                RequestNotes2 = ($scope.BuyNotes2);
                console.log(Buyer, CompanyName, ShipFirstName, ResaleNumber);
                console.log("Color: ", $scope.Color1, "Memory:", $scope.Memory1);
                var requestData = {};
                requestData = (function mapping6990($scope) {
                    var requestData = {};
                    requestData.params = {};
                    requestData.params.Buyer = Buyer;
                    requestData.params.CompanyName = CompanyName;
                    requestData.params.ShipFirstName = ShipFirstName;
                    requestData.params.ShipLastName = ShipLastName;
                    requestData.params.ShipAddress1 = ShipAddress1;
                    requestData.params.ShipAddress2 = ShipAddress2;
                    requestData.params.ShipCity = ShipCity;
                    requestData.params.ShipState = ShipState;
                    requestData.params.ShipZip = ShipZip;
                    requestData.params.Country = Country;
                    requestData.params.ResaleNumber = ResaleNumber;
                    requestData.params.ShipPhone = ShipPhone;
                    requestData.params.Manu = $scope.manufacturer1;
                    requestData.params.Prod = $scope.Product1;
                    requestData.params.Mem = $scope.Memory1;
                    requestData.params.Colour = $scope.Color1;
                    requestData.params.Cond = $scope.Condition1;
                    requestData.params.Quan = $scope.Quantity1;
                    requestData.params.BuyerNote = $scope.RNotes1;
                    requestData.params.SellerNote = $scope.OfferNotes1;
                    requestData.params.BuyingPrice = $scope.BuyerPrice1;
                    requestData.params.Shipping = $scope.Shipping1;
                    requestData.params.Offer_id = $scope._id1;
                    requestData.params.Request_id = $scope.fk_Request_id1;
                    requestData.params.Seller = $scope.Seller1;
                    requestData.params.Price = $scope.OfferPrice1;
                    requestData.params.SellingPrice = $scope.SellerPrice1;
                    requestData.params.CVC_Code = "Testing123";
                    requestData.params.BuyerNote2 = RequestNotes2;
                    requestData.params.Kit = $scope.Kitted1;
                    requestData.params.ChoiceCarrier = $scope.Carrier1;
                    requestData.params.B_Req1 = $scope.B_Requests1A;
                    requestData.params.B_Req2 = $scope.B_Requests2A;
                    requestData.params.S_Off1 = $scope.S_Offers1A;
                    requestData.params.S_Off2 = $scope.S_Offers2A;
                    return requestData;
                    /*|button_mapping|onbeforesend|C885C3B2-DBD4-E6A0-C420-3ADC71DE36C8||6990|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("InsertOrders_service")(requestData).then(
                    /*|service_bookmark|bookmark|C885C3B2-DBD4-E6A0-C420-3ADC71DE36C8||4699|*/
                    function(success) { // success callback
                        /*|button_mapping|onsuccess|C885C3B2-DBD4-E6A0-C420-3ADC71DE36C8||5103|*/
                        var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                            animation: 'slide-in-up', // The animation to show & hide with
                            focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                            backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                            hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                        };
                        Apperyio.get('Modals').loadModal("Modal_Buyer_Accept_Offer").then(
                            function(modalInstance) {
                                modalInstance.open(modalOptions).then(function(modal) {
                                    modal.scope.modal = modal;
                                    modal.scope.result = "You have Ordered the following:";
                                    modal.scope.result1 = $scope.manufacturer1;
                                    modal.scope.result2 = $scope.Product1;
                                    modal.scope.result3 = $scope.Memory1;
                                    modal.scope.result4 = $scope.Color1;
                                    modal.scope.result5 = $scope.Condition1;
                                    modal.scope.result6 = $scope.Quantity1;
                                    modal.scope.result7 = $scope.BuyerPrice1;
                                    modal.scope.result8 = $scope.Shipping1;
                                    modal.show();
                                });
                            },
                            function(error) {
                                var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                                    animation: 'slide-in-up', // The animation to show & hide with
                                    focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                                    backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                                    hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                                };
                                Apperyio.get('Modals').loadModal("Info").then(
                                    function(modalInstance) {
                                        modalInstance.open(modalOptions).then(function(modal) {
                                            modal.scope.modal = modal;
                                            modal.scope.result = "Please Try Again. There was an error";
                                            modal.show();
                                        });
                                    },
                                    function(error) {
                                        console.log(error);
                                    });
                                console.log(error);
                            });
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                Apperyio.navigateTo("Buyer_Home", {});
            };
        }
    });