define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for StepModal generated by Appery.io
         * @module StepModal
         */
        APP.controller('StepModalController', ['$scope', 'Apperyio', StepModalController]);

        function StepModalController($scope, Apperyio) {
            // user controller variables
            // user controller functions
        }
    });