define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Modal_Seller_Accept generated by Appery.io
         * @module Modal_Seller_Accept
         */
        APP.controller('Modal_Seller_AcceptController', ['$scope', 'Apperyio', Modal_Seller_AcceptController]);

        function Modal_Seller_AcceptController($scope, Apperyio) {
            // user controller variables
            $scope.RequestModel = Apperyio.EntityAPI('String');
            // user controller functions
        }
    });