define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for MessagePopup_WrongUserNamePass generated by Appery.io
         * @module MessagePopup_WrongUserNamePass
         */
        APP.controller('MessagePopup_WrongUserNamePassController', ['$scope', 'Apperyio', MessagePopup_WrongUserNamePassController]);

        function MessagePopup_WrongUserNamePassController($scope, Apperyio) {
            // user controller variables
            // user controller functions
        }
    });