define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Buyer_Home generated by Appery.io
         * @module Buyer_Home
         */
        APP.controller('Buyer_Home', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.Buyer_username = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.username = Apperyio.EntityAPI('String');
            $scope.list = Apperyio.EntityAPI('List');
            $scope.RequestID1 = Apperyio.EntityAPI('DataStorage');
            $scope.token = Apperyio.EntityAPI('String');
            $scope.inactive = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                $ionicSideMenuDelegate = Apperyio.get("$ionicSideMenuDelegate");
                $ionicSideMenuDelegate.canDragContent(true);
                var requestData = {};
                //var miniID = "";
                //Get User
                //xxxxxxxxxxxxx
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var Buyer_username = AllData.username;
                var token = AllData.session;
                var inactive = AllData.InActive;
                var active = AllData.Active;
                var textVer = AllData.TextVer;
                var emailVer = AllData.EmailVer;
                //xxxxxxxxxxxx
                //Get User  
                console.log(username);
                console.log(AllData);
                console.log(token);
                console.log("Inactive", inactive);
                console.log("Active", active);
                //console.log("len",inactive.length);
                if (active === false) {
                    alert('Your Account has been inactivated due to ' + inactive + '. Please contact customer service to resolve.');
                    var requestData = {};
                    var sessionToken = $scope.user.session;
                    console.log(sessionToken);
                    requestData = (function mapping7038($scope) {
                        var requestData = {};
                        requestData.headers = {};
                        var user_scope = $scope.user;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        return requestData;
                        /*CLICK TO EDIT MAPPING*/
                    })($scope);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("phoneapp_logout_service")(requestData).then(
                        function(success) { // success callback
                            /*CLICK TO EDIT MAPPING*/
                            Apperyio.navigateTo("Login", {});
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                } else {
                    var requestData = {};
                    requestData = (function mapping2289($scope) {
                        var requestData = {};
                        requestData.params = {};
                        var username_scope = $scope.username;
                        requestData.params.username = username;
                        requestData.headers = {};
                        var token_scope = $scope.token;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        console.log("token", token);
                        return requestData;
                        /*|button_mapping|onbeforesend|214D4B44-2CB9-E04C-0C76-E5BF1F8E43B9||2289|*/
                    })($scope);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("ReturnOffersToBuyer_service")(requestData).then(
                        /*|service_bookmark|bookmark|214D4B44-2CB9-E04C-0C76-E5BF1F8E43B9||4587|*/
                        function(success) { // success callback
                            (function mapping6258(success, $scope) {
                                var list_scope = $scope.list;
                                list_scope = success.data;
                                $scope.list = list_scope;
                                console.log($scope.list)
                                /*|button_mapping|onsuccess|214D4B44-2CB9-E04C-0C76-E5BF1F8E43B9||6258|*/
                            })(success, $scope);
                        },
                        function(error) { // callback to handle request error
                            //Apperyio.navigateTo("Login", {});
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //Check for packages to Ship
                    var requestData = {};
                    requestData = (function mapping8056($scope) {
                        var requestData = {};
                        requestData.params = {};
                        var Seller_username_scope = $scope.Seller_username;
                        requestData.params.username = username;
                        requestData.headers = {};
                        var token_scope = $scope.token;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        console.log("token", token);
                        console.log("Sellerundercount", username);
                        return requestData;
                        /*CLICK TO EDIT MAPPING*/
                    })($scope);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("Buyer_Home_Shipped_service")(requestData).then(
                        function(success) { // success callback
                            (function mapping2821(success, $scope) {
                                var unshippedCount_scope = $scope.unshippedCount;
                                unshippedCount_scope = success.data[0].count;
                                $scope.unshippedCount = unshippedCount_scope;
                                console.log("Count", $scope.unshippedCount);
                                // $scope.count2 = unshippedCount_scope;
                                // console.log("Count2",$scope.count2);
                                //Below this is whether the items are shipped or not
                                if ($scope.unshippedCount === 0) {
                                    $scope.dsblBtn = true;
                                    $scope.showBtn = false;
                                    $scope.wordBtn = "There are NO items that are shippping";
                                } else {
                                    $scope.dsblBtn = false;
                                    $scope.showBtn = true;
                                    $scope.wordBtn = $scope.unshippedCount + " shipped items";
                                    $scope.badgeCnt = $scope.unshippedCount;
                                }
                                //$scope.dsblBtn = false;
                                console.log("showBtn", $scope.showBtn);
                                /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //see if email and/or phone has be verified
                    if (textVer === false || emailVer === false) {
                        $scope.wordBtn1 = "You need to VERIFY your info";
                        $scope.showBtn1 = true;
                        $scope.badgeCnt1 = 1;
                    } else {}
                }
            };
            /**
             * @function showDetail
             * @param _id
             */
            $scope.showDetail = function(_id) {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = _id
                console.log(_id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                Apperyio.navigateTo("Buyer_Accept_Offer");
            };
            /**
             * @function gotoBuyer_Test
             */
            $scope.gotoBuyer_Test = function() {
                Apperyio.navigateTo("Test", {});
            };
            /**
             * @function reload
             */
            $scope.reload = function() {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.whereami = "Buyer_Home";
                //console.log(_id);
                Apperyio.navigateTo("PassThru", {});
            };
        }
    });