define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Buyer_Home generated by Appery.io
         * @module Buyer_Home
         */
        APP.controller('Buyer_Home', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.Buyer_username = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.username = Apperyio.EntityAPI('String');
            $scope.list = Apperyio.EntityAPI('List');
            $scope.RequestID1 = Apperyio.EntityAPI('DataStorage');
            $scope.token = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var requestData = {};
                //var miniID = "";
                //Get User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var Buyer_username = AllData.username;
                var token = AllData.session;
                //Get User  
                console.log(username);
                console.log(AllData);
                console.log(token);
                var requestData = {};
                requestData = (function mapping2289($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var username_scope = $scope.username;
                    requestData.params.username = username;
                    requestData.headers = {};
                    var token_scope = $scope.token;
                    requestData.headers['X-Appery-Session-Token'] = token;
                    console.log("token", token);
                    return requestData;
                    /*|button_mapping|onbeforesend|214D4B44-2CB9-E04C-0C76-E5BF1F8E43B9||2289|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("ReturnOffersToBuyer_service")(requestData).then(
                    /*|service_bookmark|bookmark|214D4B44-2CB9-E04C-0C76-E5BF1F8E43B9||4587|*/
                    function(success) { // success callback
                        (function mapping6258(success, $scope) {
                            var list_scope = $scope.list;
                            list_scope = success.data;
                            $scope.list = list_scope;
                            console.log($scope.list)
                            /*|button_mapping|onsuccess|214D4B44-2CB9-E04C-0C76-E5BF1F8E43B9||6258|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        Apperyio.navigateTo("Login", {});
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function showDetail
             * @param _id
             */
            $scope.showDetail = function(_id) {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = _id
                console.log(_id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                Apperyio.navigateTo("Buyer_Accept_Offer");
            };
            /**
             * @function gotoBuyer_Test
             */
            $scope.gotoBuyer_Test = function() {
                Apperyio.navigateTo("Screen1", {});
            };
            /**
             * @function reload
             */
            $scope.reload = function() {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.whereami = "Buyer_Home";
                //console.log(_id);
                Apperyio.navigateTo("PassThru", {});
            };
        }
    });