define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Modal_Buyer_Request generated by Appery.io
         * @module Modal_Buyer_Request
         */
        APP.controller('Modal_Buyer_RequestController', ['$scope', 'Apperyio', Modal_Buyer_RequestController]);

        function Modal_Buyer_RequestController($scope, Apperyio) {
            // user controller variables
            $scope.RequestModel = Apperyio.EntityAPI('String');
            // user controller functions
        }
    });