define(['require'],
    function(require) {
        /**
         * Controller for index generated by Appery.io
         * @module index
         */
        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.activeScreen = Apperyio.EntityAPI('ActiveScreen');
            $scope.User = Apperyio.EntityAPI('User');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                $scope.visionStatus = {};
                $scope.RequestID = {
                    current: 0
                };
            };
            /**
             * @function gotoPage
             */
            $scope.gotoPage = function() {
                var userData = Apperyio.get("dataStorage");
                //userData.current = success.data;
                // Apperyio.navigateTo("Welcome", {});
                var AllData = userData.current;
                var turn = AllData.UserType
                if (turn == "B") {
                    Apperyio.navigateTo("Buyer_Home", {});
                } else {
                    Apperyio.navigateTo("Seller_Home", {});
                }
            };
            /**
             * @function gotoBuyerInProcess
             */
            $scope.gotoBuyerInProcess = function() {
                Apperyio.navigateTo("Buyer_InProcess", {});
            };
            /**
             * @function gotoBuyerMakeRequest
             */
            $scope.gotoBuyerMakeRequest = function() {
                Apperyio.navigateTo("Buyer_MakeRequest", {});
            };
            /**
             * @function gotoBuyerComplete
             */
            $scope.gotoBuyerComplete = function() {
                Apperyio.navigateTo("Buyer_Complete", {});
            };
            /**
             * @function gotoBuyerHome
             */
            $scope.gotoBuyerHome = function() {
                Apperyio.navigateTo("Buyer_Home", {});
            };
            /**
             * @function gotoBuyerRequestSee
             */
            $scope.gotoBuyerRequestSee = function() {
                Apperyio.navigateTo("Buyer_Requests_See", {});
            };
            /**
             * @function gotoSellerHome
             */
            $scope.gotoSellerHome = function() {
                Apperyio.navigateTo("Seller_Home", {});
            };
            /**
             * @function gotoSellerInProcess
             */
            $scope.gotoSellerInProcess = function() {
                Apperyio.navigateTo("Seller_InProcess", {});
            };
            /**
             * @function gotoSellerComplete
             */
            $scope.gotoSellerComplete = function() {
                Apperyio.navigateTo("Seller_Complete", {});
            };
            /**
             * @function gotoSellerAccepted
             */
            $scope.gotoSellerAccepted = function() {
                Apperyio.navigateTo("Seller_Accepted", {});
            };
            /**
             * @function gotoSellerOffers
             */
            $scope.gotoSellerOffers = function() {
                Apperyio.navigateTo("Seller_Offers", {});
            };
        }
        return ['$scope', 'Apperyio', controller];
    });