define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for sq_iFrame generated by Appery.io
         * @module sq_iFrame
         */
        APP.controller('sq_iFrame', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.username = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var custID = AllData.sqCustID;
                //xxxxxxxxxxxx
                //Get User  
                //console.log(username);
                //console.log(AllData);
                //console.log(custID);
                var urlstring = "https://app.thephoneex.com/entercc.html";
                var builturl = urlstring + "?" + "username=" + username + "&custID=" + custID;
                var $sce = Apperyio.get("$sce");
                $scope.builturl = $sce.trustAsResourceUrl(builturl);
                //console.log(builturl);
            };
            /**
             * @function goBank
             */
            $scope.goBank = function() {
                Apperyio.navigateTo("Bank", {});
            };
        }
    });