define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Modal_Buyer_Enter_Complete generated by Appery.io
         * @module Modal_Buyer_Enter_Complete
         */
        APP.controller('Modal_Buyer_Enter_CompleteController', ['$scope', 'Apperyio', Modal_Buyer_Enter_CompleteController]);

        function Modal_Buyer_Enter_CompleteController($scope, Apperyio) {
            // user controller variables
            $scope.RequestModel = Apperyio.EntityAPI('String');
            // user controller functions
        }
    });