define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Privacy_Terms generated by Appery.io
         * @module Privacy_Terms
         */
        APP.controller('Privacy_TermsController', ['$scope', 'Apperyio', Privacy_TermsController]);

        function Privacy_TermsController($scope, Apperyio) {
            // user controller variables
            // user controller functions
        }
    });