define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Modal_Seller_Enter_Tracking generated by Appery.io
         * @module Modal_Seller_Enter_Tracking
         */
        APP.controller('Modal_Seller_Enter_TrackingController', ['$scope', 'Apperyio', Modal_Seller_Enter_TrackingController]);

        function Modal_Seller_Enter_TrackingController($scope, Apperyio) {
            // user controller variables
            $scope.RequestModel = Apperyio.EntityAPI('String');
            // user controller functions
        }
    });