define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Seller_Home generated by Appery.io
         * @module Seller_Home
         */
        APP.controller('Seller_Home', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.list = Apperyio.EntityAPI('List');
            $scope.Buyer_username = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.username = Apperyio.EntityAPI('String');
            $scope.item = Apperyio.EntityAPI('String');
            $scope.Product_Temp = Apperyio.EntityAPI('String');
            $scope.RequestID1 = Apperyio.EntityAPI('DataStorage');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var item = "";
                var requestData = {};
                /*|button_mapping|onbeforesend|18190B81-E92A-513F-EB9A-826B12BB512A||6269|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("Requests_Seller_service")(requestData).then(
                    /*|service_bookmark|bookmark|18190B81-E92A-513F-EB9A-826B12BB512A||9756|*/
                    function(success) { // success callback
                        (function mapping9396(success, $scope) {
                            var list_scope = $scope.list;
                            list_scope = success.data;
                            $scope.list = list_scope;
                            /*|button_mapping|onsuccess|18190B81-E92A-513F-EB9A-826B12BB512A||9698|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function showDetail
             * @param _id
             */
            $scope.showDetail = function(_id) {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = _id
                console.log(_id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                Apperyio.navigateTo("Seller_Accept_Request");
            };
        }
    });