define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Seller_Home generated by Appery.io
         * @module Seller_Home
         */
        APP.controller('Seller_Home', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.list = Apperyio.EntityAPI('List');
            $scope.Seller_username = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.username = Apperyio.EntityAPI('String');
            $scope.item = Apperyio.EntityAPI('String');
            $scope.Product_Temp = Apperyio.EntityAPI('String');
            $scope.RequestID1 = Apperyio.EntityAPI('DataStorage');
            $scope.token = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var Seller_username = AllData.username;
                var token = AllData.session;
                //Get User  
                console.log("SellerUser:", Seller_username);
                var item = "";
                var requestData = {};
                requestData = (function mapping6269($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var Seller_username_scope = $scope.Seller_username;
                    requestData.params.username = Seller_username;
                    requestData.headers = {};
                    var token_scope = $scope.token;
                    requestData.headers['X-Appery-Session-Token'] = token;
                    console.log("token", token);
                    return requestData;
                    /*|button_mapping|onbeforesend|18190B81-E92A-513F-EB9A-826B12BB512A||6269|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("Requests_Seller_service")(requestData).then(
                    /*|service_bookmark|bookmark|18190B81-E92A-513F-EB9A-826B12BB512A||9756|*/
                    function(success) { // success callback
                        (function mapping9396(success, $scope) {
                            var list_scope = $scope.list;
                            list_scope = success.data;
                            $scope.list = list_scope;
                            /*|button_mapping|onsuccess|18190B81-E92A-513F-EB9A-826B12BB512A||9698|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        Apperyio.navigateTo("Login", {});
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function showDetail
             * @param _id
             */
            $scope.showDetail = function(_id) {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = _id
                console.log(_id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                Apperyio.navigateTo("Seller_Accept_Request");
            };
        }
    });