define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Seller_Home generated by Appery.io
         * @module Seller_Home
         */
        APP.controller('Seller_Home', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.list = Apperyio.EntityAPI('List');
            $scope.Seller_username = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.username = Apperyio.EntityAPI('String');
            $scope.item = Apperyio.EntityAPI('String');
            $scope.Product_Temp = Apperyio.EntityAPI('String');
            $scope.RequestID1 = Apperyio.EntityAPI('DataStorage');
            $scope.token = Apperyio.EntityAPI('String');
            $scope.inactive = Apperyio.EntityAPI('String');
            $scope.unshippedCount = Apperyio.EntityAPI('String');
            $scope.dsblBtn = Apperyio.EntityAPI('Boolean');
            $scope.wordBtn = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                $ionicSideMenuDelegate = Apperyio.get("$ionicSideMenuDelegate");
                $ionicSideMenuDelegate.canDragContent(true);
                var dsblBtn = true;
                $scope.showBtn = true;
                //On load screen logic
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var Seller_username = AllData.username;
                var token = AllData.session;
                var inactive = AllData.InActive;
                var active = AllData.Active;
                var textVer = AllData.TextVer;
                var emailVer = AllData.EmailVer;
                //Get User  
                console.log("SellerUser:", Seller_username);
                console.log("Active:", active);
                if (active === false) {
                    alert('Your Account has been inactivated due to ' + inactive + '. Please contact customer service to resolve.');
                    var requestData = {};
                    var sessionToken = $scope.user.session;
                    console.log(sessionToken);
                    requestData = (function mapping7038($scope) {
                        var requestData = {};
                        requestData.headers = {};
                        var user_scope = $scope.user;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        return requestData;
                        /*CLICK TO EDIT MAPPING*/
                    })($scope);
                    //read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("phoneapp_logout_service")(requestData).then(
                        function(success) { // success callback
                            /*CLICK TO EDIT MAPPING*/
                            Apperyio.navigateTo("Login", {});
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                } else {
                    var item = "";
                    var requestData = {};
                    requestData = (function mapping6269($scope) {
                        var requestData = {};
                        requestData.params = {};
                        var Seller_username_scope = $scope.Seller_username;
                        requestData.params.username = Seller_username;
                        requestData.headers = {};
                        var token_scope = $scope.token;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        console.log("token", token);
                        return requestData;
                        /*|button_mapping|onbeforesend|18190B81-E92A-513F-EB9A-826B12BB512A||6269|*/
                    })($scope);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("Requests_Seller_service")(requestData).then(
                        /*|service_bookmark|bookmark|18190B81-E92A-513F-EB9A-826B12BB512A||9756|*/
                        function(success) { // success callback
                            (function mapping9396(success, $scope) {
                                var list_scope = $scope.list;
                                list_scope = success.data;
                                $scope.list = list_scope;
                                /*|button_mapping|onsuccess|18190B81-E92A-513F-EB9A-826B12BB512A||9698|*/
                            })(success, $scope);
                        },
                        function(error) { // callback to handle request error
                            //Apperyio.navigateTo("Login", {});
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //Check for packages to Ship
                    var requestData = {};
                    requestData = (function mapping8056($scope) {
                        var requestData = {};
                        requestData.params = {};
                        var Seller_username_scope = $scope.Seller_username;
                        requestData.params.username = Seller_username;
                        requestData.headers = {};
                        var token_scope = $scope.token;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        console.log("token", token);
                        console.log("Sellerundercount", Seller_username);
                        return requestData;
                        /*|button_mapping|onbeforesend|74ACF7FD-6A4B-49C1-D279-461019F09F73||8056|*/
                    })($scope);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("Seller_Accepted_Seller_Orders_NotShipped_Count_service")(requestData).then(
                        /*|service_bookmark|bookmark|74ACF7FD-6A4B-49C1-D279-461019F09F73||2436|*/
                        function(success) { // success callback
                            (function mapping2821(success, $scope) {
                                var unshippedCount_scope = $scope.unshippedCount;
                                unshippedCount_scope = success.data[0].count;
                                $scope.unshippedCount = unshippedCount_scope;
                                console.log("Count", $scope.unshippedCount);
                                // $scope.count2 = unshippedCount_scope;
                                // console.log("Count2",$scope.count2);
                                //Below this is whether the items are shipped or not
                                if ($scope.unshippedCount === 0) {
                                    $scope.dsblBtn = true;
                                    $scope.showBtn = false;
                                    $scope.wordBtn = "There are NO items to ship";
                                } else {
                                    $scope.dsblBtn = false;
                                    $scope.showBtn = true;
                                    $scope.wordBtn = $scope.unshippedCount + " accepted offers";
                                    $scope.badgeCnt = $scope.unshippedCount;
                                }
                                //$scope.dsblBtn = false;
                                console.log("showBtn", $scope.showBtn);
                                /*|button_mapping|onsuccess|74ACF7FD-6A4B-49C1-D279-461019F09F73||2821|*/
                            })(success, $scope);
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //see if email and/or phone has be verified
                    if (textVer === false || emailVer === false) {
                        $scope.wordBtn1 = "You need to VERIFY your info";
                        $scope.showBtn1 = true;
                        $scope.badgeCnt1 = 1;
                    } else {}
                }
            };
            /**
             * @function showDetail
             * @param _id
             */
            $scope.showDetail = function(_id) {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = _id
                console.log(_id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                Apperyio.navigateTo("Seller_Accept_Request");
            };
            /**
             * @function gotoFilter
             */
            $scope.gotoFilter = function() {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.whereami = "Seller_Filter";
                //console.log(_id);
                Apperyio.navigateTo("PassThru", {});
            };
        }
    });