define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Welcome generated by Appery.io
         * @module Welcome
         */
        APP.controller('Welcome', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.username1 = Apperyio.EntityAPI('String');
            $scope.main = Apperyio.EntityAPI('Main');
            $scope.user_id = Apperyio.EntityAPI('String');
            $scope.userp = Apperyio.EntityAPI('String');
            $scope.userProfile_id = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                //xxxxxxxxxxxxx
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var dev_user = AllData.username;
                $scope.main.username1 = AllData.username;
                var token = AllData.session;
                //xxxxxxxxxxxx
                console.log(userData);
                //The next lines are added to get the deviceid and register push notifications
                //Thenext line was added to get user
                //next two lines were original
                //$scope.timeZone = "GMT-04:00";
                //document.addEventListener("push-notification", function(event) {alert(event.detail.message);});
                //new code here:
                $scope.timeZone = "GMT-04:00";
                //orig below line
                //document.addEventListener("push-notification", function(event) {alert(event.detail.message);});
                //added newto go Home
                document.addEventListener("push-notification", function(event) {
                    alert(event.detail.message);
                    //Apperyio.navigateTo("Buyer_Ins");
                    //alert('Go to your Home screen and click refresh to see your alerts');
                    if (turn == "B") {
                        // inject the 'dataStorage' service
                        var data = Apperyio.get("dataStorage");
                        $scope.RequestID1.Gl_Vars = data;
                        $scope.RequestID1.Gl_Vars.whereami = "Buyer_Home";
                        //console.log(_id);
                        Apperyio.navigateTo("PassThru", {});
                    } else {
                        // inject the 'dataStorage' service
                        var data = Apperyio.get("dataStorage");
                        $scope.RequestID1.Gl_Vars = data;
                        $scope.RequestID1.Gl_Vars.whereami = "Seller_Home";
                        //console.log(_id);
                        Apperyio.navigateTo("PassThru", {});
                    }
                });
                var requestData = {};
                /*|button_mapping|onbeforesend|E66F2CF9-EFE8-065B-71B1-9FDF8075B3BE||8079|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("PushRegisterDevice")(requestData).then(
                    /*|service_bookmark|bookmark|E66F2CF9-EFE8-065B-71B1-9FDF8075B3BE||2407|*/
                    function(success) { // success callback
                        (function mapping4691(success, $scope) {
                            var main_scope = $scope.main;
                            _.set(main_scope, 'devID1', success.deviceID);
                            _.set(main_scope, 'object_id1', success._id);
                            $scope.main = main_scope;
                            alert("Login Success. \n" + "Device ID: " + $scope.main.devID1 + "   ObjectID:" + $scope.main.object_id1 + " User:" + $scope.main.username1);
                            /*|button_mapping|onsuccess|E66F2CF9-EFE8-065B-71B1-9FDF8075B3BE||4691|*/
                            // here is the part where it marries device and user
                            var requestData = {};
                            requestData = (function mapping4208($scope) {
                                var requestData = {};
                                requestData.params = {};
                                var main_scope = $scope.main;
                                requestData.params.user = main_scope.username1;
                                requestData.params.Device_id = main_scope.object_id1;
                                return requestData;
                                /*|button_mapping|onbeforesend|6FD719F6-E598-1DB9-4853-034AE70A950F||4208|*/
                            })($scope);
                            // read more about using rest services: https://links.appery.io/ve-snippet-rest
                            Apperyio.get("Insert_User_Device_service")(requestData).then(
                                /*|service_bookmark|bookmark|6FD719F6-E598-1DB9-4853-034AE70A950F||2652|*/
                                function(success) { // success callback
                                    /*|button_mapping|onsuccess|6FD719F6-E598-1DB9-4853-034AE70A950F||4970|*/
                                },
                                function(error) { // callback to handle request error
                                },
                                function(notify) { // notify callback, can fire few times
                                });
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                requestData = (function mapping4873($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var username1_scope = $scope.username1;
                    requestData.params.username = username;
                    console.log("username", username);
                    return requestData;
                    /*|button_mapping|onbeforesend|16AF4360-5080-3A4C-D40A-892FFC452EAA||4873|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("Get_user_id_profileId_service")(requestData).then(
                    /*|service_bookmark|bookmark|16AF4360-5080-3A4C-D40A-892FFC452EAA||5217|*/
                    function(success) { // success callback
                        (function mapping6029(success, $scope) {
                            var userProfile_id_scope = $scope.userProfile_id;
                            var user_id_scope = $scope.user_id;
                            userProfile_id_scope = success.data.body[0].toProfile._id;
                            user_id_scope = success.data.body[0]._id;
                            $scope.userProfile_id = userProfile_id_scope;
                            $scope.user_id = user_id_scope;
                            /*|button_mapping|onsuccess|16AF4360-5080-3A4C-D40A-892FFC452EAA||6029|*/
                        })(success, $scope);
                        userData.current.user_id = $scope.user_id;
                        userData.current.profile_id = $scope.userProfile_id;
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function gotoInstructions
             */
            $scope.gotoInstructions = function() {
                var userData = Apperyio.get("dataStorage");
                //userData.current = success.data;
                // Apperyio.navigateTo("Welcome", {});
                var AllData = userData.current;
                var turn = AllData.UserType
                if (turn == "B") {
                    //new part between comments to get menu**************************************************
                    // REgister menu for buyers - Change Menu - Log everyone out
                    //var requestData = {};
                    /*CLICK TO EDIT MAPPING*/
                    //new
                    //localStorage.clear();
                    //working on this part
                    var myString2 = "B";
                    localStorage.setItem("localStorageString1", myString2); // set the value
                    console.log("mystringatlogin", myString2);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("getMenu1_service")(requestData).then(
                        function(success) { // success callback
                            (function mapping8022(success, $scope) {
                                var tempmenu1_scope = $scope.tempmenu1;
                                tempmenu1_scope = success.data;
                                $scope.tempmenu1 = tempmenu1_scope;
                                /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);
                            var myStringArray1 = JSON.stringify($scope.tempmenu1);
                            localStorage.setItem("localStorageStringArray1", myStringArray1); // set the value
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //var requestData = {};
                    /*CLICK TO EDIT MAPPING*/
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("getMenu2_service")(requestData).then(
                        function(success) { // success callback
                            (function mapping7075(success, $scope) {
                                var tempmenu2_scope = $scope.tempmenu2;
                                tempmenu2_scope = success.data;
                                $scope.tempmenu2 = tempmenu2_scope;
                                /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);
                            var myStringArray2 = JSON.stringify($scope.tempmenu2);
                            localStorage.setItem("localStorageStringArray2", myStringArray2); // set the value
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //var requestData = {};
                    /*CLICK TO EDIT MAPPING*/
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("getMenu3_service")(requestData).then(
                        function(success) { // success callback
                            (function mapping5631(success, $scope) {
                                var tempmenu3_scope = $scope.tempmenu3;
                                tempmenu3_scope = success.data;
                                $scope.tempmenu3 = tempmenu3_scope;
                                /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);
                            var myStringArray3 = JSON.stringify($scope.tempmenu3);
                            localStorage.setItem("localStorageStringArray3", myStringArray3); // set the value
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //var requestData = {};
                    /*CLICK TO EDIT MAPPING*/
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("getMenu4_service")(requestData).then(
                        function(success) { // success callback
                            (function mapping3047(success, $scope) {
                                var tempmenu4_scope = $scope.tempmenu4;
                                tempmenu4_scope = success.data;
                                $scope.tempmenu4 = tempmenu4_scope;
                                /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);
                            var myStringArray4 = JSON.stringify($scope.tempmenu4);
                            localStorage.setItem("localStorageStringArray4", myStringArray4); // set the value
                            console.log("I am on the indexPage");
                            console.log("myArray4_index", myStringArray4)
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //var requestData = {};
                    /*CLICK TO EDIT MAPPING*/
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("getMenu5_service")(requestData).then(
                        function(success) { // success callback
                            (function mapping8710(success, $scope) {
                                var tempmenu5_scope = $scope.tempmenu5;
                                tempmenu5_scope = success.data;
                                $scope.tempmenu5 = tempmenu5_scope;
                                /*CLICK TO EDIT MAPPING*/
                            })(success, $scope);
                            var myStringArray5 = JSON.stringify($scope.tempmenu5);
                            localStorage.setItem("localStorageStringArray5", myStringArray5); // set the value
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    //new part between comments to get menu**************************************************
                    Apperyio.navigateTo("Buyer_Ins", {
                        'reloadPage': true
                    });
                } else {
                    Apperyio.navigateTo("Seller_Ins", {
                        'reloadPage': true
                    });
                }
            };
        }
    });