define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Welcome generated by Appery.io
         * @module Welcome
         */
        APP.controller('Welcome', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.username1 = Apperyio.EntityAPI('String');
            $scope.main = Apperyio.EntityAPI('Main');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                //xxxxxxxxxxxxx
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var dev_user = AllData.username;
                $scope.main.username1 = AllData.username;
                var token = AllData.session;
                //xxxxxxxxxxxx
                console.log(userData);
                //The next lines are added to get the deviceid and register push notifications
                //Thenext line was added to get user
                $scope.timeZone = "GMT-04:00";
                document.addEventListener("push-notification", function(event) {
                    alert(event.detail.message);
                });
                var requestData = {};
                /*|button_mapping|onbeforesend|E66F2CF9-EFE8-065B-71B1-9FDF8075B3BE||8079|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("PushRegisterDevice")(requestData).then(
                    /*|service_bookmark|bookmark|E66F2CF9-EFE8-065B-71B1-9FDF8075B3BE||2407|*/
                    function(success) { // success callback
                        (function mapping4691(success, $scope) {
                            var main_scope = $scope.main;
                            _.set(main_scope, 'devID1', success.deviceID);
                            _.set(main_scope, 'object_id1', success._id);
                            $scope.main = main_scope;
                            alert("Login Success. \n" + "Device ID: " + $scope.main.devID1 + "   ObjectID:" + $scope.main.object_id1 + " User:" + $scope.main.username1);
                            /*|button_mapping|onsuccess|E66F2CF9-EFE8-065B-71B1-9FDF8075B3BE||4691|*/
                            // here is the part where it marries device and user
                            var requestData = {};
                            requestData = (function mapping4208($scope) {
                                var requestData = {};
                                requestData.params = {};
                                var main_scope = $scope.main;
                                requestData.params.user = main_scope.username1;
                                requestData.params.Device_id = main_scope.object_id1;
                                return requestData;
                                /*|button_mapping|onbeforesend|6FD719F6-E598-1DB9-4853-034AE70A950F||4208|*/
                            })($scope);
                            // read more about using rest services: https://links.appery.io/ve-snippet-rest
                            Apperyio.get("Insert_User_Device_service")(requestData).then(
                                /*|service_bookmark|bookmark|6FD719F6-E598-1DB9-4853-034AE70A950F||2652|*/
                                function(success) { // success callback
                                    /*|button_mapping|onsuccess|6FD719F6-E598-1DB9-4853-034AE70A950F||4970|*/
                                },
                                function(error) { // callback to handle request error
                                },
                                function(notify) { // notify callback, can fire few times
                                });
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function gotoInstructions
             */
            $scope.gotoInstructions = function() {
                var userData = Apperyio.get("dataStorage");
                //userData.current = success.data;
                // Apperyio.navigateTo("Welcome", {});
                var AllData = userData.current;
                var turn = AllData.UserType
                if (turn == "B") {
                    Apperyio.navigateTo("Buyer_Ins", {
                        'reloadPage': true
                    });
                } else {
                    Apperyio.navigateTo("Seller_Ins", {
                        'reloadPage': true
                    });
                }
            };
        }
    });