define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Seller_Offers generated by Appery.io
         * @module Seller_Offers
         */
        APP.controller('Seller_Offers', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.Buyer_username = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.username1 = Apperyio.EntityAPI('String');
            $scope.list = Apperyio.EntityAPI('List');
            $scope.RequestID1 = Apperyio.EntityAPI('DataStorage');
            $scope.token = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var requestData = {};
                //var miniID = "";
                //Get User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var username = AllData.username;
                var username1 = AllData.username;
                var token = AllData.session;
                //Get User  
                console.log("UserName:", username1);
                var requestData = {};
                requestData = (function mapping4817($scope) {
                    var requestData = {};
                    requestData.params = {};
                    var username1_scope = username1;
                    requestData.params.username = username1_scope;
                    console.log(username1_scope);
                    requestData.headers = {};
                    var token_scope = $scope.token;
                    requestData.headers['X-Appery-Session-Token'] = token;
                    console.log("token", token);
                    return requestData;
                    /*|button_mapping|onbeforesend|AC0255D2-AA14-57BC-1A9E-35623C94024F||4817|*/
                })($scope);
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("ReturnOffersToSeller_service")(requestData).then(
                    /*|service_bookmark|bookmark|AC0255D2-AA14-57BC-1A9E-35623C94024F||9830|*/
                    function(success) { // success callback
                        (function mapping4862(success, $scope) {
                            var list_scope = $scope.list;
                            list_scope = success.data;
                            $scope.list = list_scope;
                            /*|button_mapping|onsuccess|AC0255D2-AA14-57BC-1A9E-35623C94024F||4862|*/
                        })(success, $scope);
                    },
                    function(error) { // callback to handle request error
                        //Apperyio.navigateTo("Login", {});
                    },
                    function(notify) { // notify callback, can fire few times
                    });
            };
            /**
             * @function showDetail
             * @param _id
             */
            $scope.showDetail = function(_id) {
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = _id;
                console.log(_id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                Apperyio.navigateTo("Seller_Offers_Detail");
            };
        }
    });