define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Seller_Filter generated by Appery.io
         * @module Seller_Filter
         */
        APP.controller('Seller_Filter', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.token = Apperyio.EntityAPI('String');
            $scope.tempmenu1 = Apperyio.EntityAPI('Array');
            $scope.tempmenu2 = Apperyio.EntityAPI('Array');
            $scope.tempmenu3 = Apperyio.EntityAPI('Array');
            $scope.RequestManu = Apperyio.EntityAPI('String');
            $scope.RequestType = Apperyio.EntityAPI('String');
            $scope.RequestModel = Apperyio.EntityAPI('String');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                //menu1 Recall
                var myStringArray1 = localStorage.getItem("localStorageStringArray1");
                var currentArray1 = [];
                currentArray1 = JSON.parse(myStringArray1);
                //var myVar = localStorage.getItem(myVar); // get the value
                console.log("lowermenu", currentArray1);
                //menu2 Recall
                var myStringArray2 = localStorage.getItem("localStorageStringArray2");
                var currentArray2 = [];
                currentArray2 = JSON.parse(myStringArray2);
                //var myVar = localStorage.getItem(myVar); // get the value
                console.log("lowermenu2", currentArray2);
                //menu3 Recall
                var myStringArray3 = localStorage.getItem("localStorageStringArray3");
                var currentArray3 = [];
                currentArray3 = JSON.parse(myStringArray3);
                //var myVar = localStorage.getItem(myVar); // get the value
                console.log("lowermenu3", currentArray3);
                var pass = {};
                $scope.company = {};
                $scope.type = {};
                $scope.model = {};
                $scope.storage = {};
                $scope.finish = {};
                var allCompanies = currentArray1;
                var allTypes = currentArray2;
                var allModels = currentArray3;
                var allStorages = [];
                $scope.companies = allCompanies;
                $scope.$watch('company', function() {
                    $scope.types = allTypes.filter(function(s) {
                        return s.CompanyId == $scope.company.Id;
                    });
                    //$scope.city = {};
                    $scope.type = {};
                    $scope.models = [];
                });
                $scope.$watch('type', function() {
                    $scope.models = allModels.filter(function(c) {
                        return c.TypeId == $scope.type.Id;
                    });
                    $scope.city = {};
                });
                $scope.$watch('model', function() {
                    $scope.storages = allStorages.filter(function(c) {
                        return c.ModelId == $scope.model.Id;
                    });
                    //Check to see if its a Cellular 
                    if ($scope.type.Id == 3) {
                        $scope.model.ModelName = $scope.model.ModelName + " - Cellular";
                    } else {
                        $scope.model.ModelName = $scope.model.ModelName;
                    }
                    $scope.storage = {};
                });
            };
            /**
             * @function toFilter
             */
            $scope.toFilter = function() {
                //Get User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var token = AllData.session;
                var RequestManu = "noChoice";
                var RequestType = "noChoice";
                var RequestModel = "noChoice";
                //Get User     
                console.log(token);
                RequestManu = ($scope.company.CompanyName);
                RequestType = ($scope.type.TypeName);
                RequestModel = ($scope.model.ModelName);
                console.log("RequestManu", RequestManu);
                console.log("RequestType", RequestType);
                console.log("RequestModel", RequestModel);
                if (RequestManu === undefined) {
                    RequestManu = "noChoice";
                } else {}
                if (RequestType === undefined) {
                    RequestType = "noChoice";
                } else {}
                if (RequestModel === undefined) {
                    RequestModel = "noChoice";
                } else {}
                if (RequestType === undefined) {
                    RequestType = "noChoice";
                } else {}
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID1.Gl_Vars = data;
                $scope.RequestID1.Gl_Vars.request_id = token;
                $scope.RequestID1.Gl_Vars.request_id2 = RequestManu;
                $scope.RequestID1.Gl_Vars.request_id3 = RequestType;
                $scope.RequestID1.Gl_Vars.request_id4 = RequestModel;
                //console.log(id);
                console.log($scope.RequestID1.Gl_Vars.request_id);
                console.log($scope.RequestID1.Gl_Vars.request_id2);
                console.log($scope.RequestID1.Gl_Vars.request_id3);
                console.log($scope.RequestID1.Gl_Vars.request_id4);
                Apperyio.navigateTo("Seller_Filter_Home");
            };
        }
    });