define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for PassThru generated by Appery.io
         * @module PassThru
         */
        APP.controller('PassThru', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.RequestID2 = Apperyio.EntityAPI('DataStorage');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                //On load screen logic
                var RequestID3 = ""
                // inject the 'dataStorage' service
                var data = Apperyio.get("dataStorage");
                // user1 is a variable in the page1 scope 
                // set it to reference the 'dataStorage' service
                $scope.RequestID2.Gl_Vars = data;
                //console.log($scope.RequestID2.Gl_Vars.request_id);
                RequestID3 = $scope.RequestID2.Gl_Vars.whereami;
                //console.log("RequestID3= ",RequestID3);
                Apperyio.navigateTo(RequestID3, {
                    'reloadPage': true
                });
            };
        }
    });