define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for RegistrationComplete generated by Appery.io
         * @module RegistrationComplete
         */
        APP.controller('RegistrationCompleteController', ['$scope', 'Apperyio', RegistrationCompleteController]);

        function RegistrationCompleteController($scope, Apperyio) {
            // user controller variables
            // user controller functions
        }
    });