define(['require', 'app'],
    function(require, APP) {
        /**
         * Controller for Buyer_MakeRequest generated by Appery.io
         * @module Buyer_MakeRequest
         */
        APP.controller('Buyer_MakeRequest', ['$scope', 'Apperyio', controller]);

        function controller($scope, Apperyio) {
            /**
             * user controller variables
             */
            $scope.token = Apperyio.EntityAPI('String');
            $scope.RequestManu = Apperyio.EntityAPI('String');
            $scope.RequestType = Apperyio.EntityAPI('String');
            $scope.RequestModel = Apperyio.EntityAPI('String');
            $scope.RequestMem = Apperyio.EntityAPI('String');
            $scope.RequestColor = Apperyio.EntityAPI('String');
            $scope.user = Apperyio.EntityAPI('User');
            $scope.RequestCarrier = Apperyio.EntityAPI('String');
            $scope.RequestKitted = Apperyio.EntityAPI('String');
            $scope.RequestQuan = Apperyio.EntityAPI('String');
            $scope.RequestExpiration = Apperyio.EntityAPI('String');
            $scope.RequestShipping = Apperyio.EntityAPI('String');
            $scope.tempmenu1 = Apperyio.EntityAPI('Array');
            $scope.tempmenu2 = Apperyio.EntityAPI('Array');
            $scope.tempmenu3 = Apperyio.EntityAPI('Array');
            $scope.tempmenu4 = Apperyio.EntityAPI('Array');
            $scope.tempmenu5 = Apperyio.EntityAPI('Array');
            /**
             * User controller functions
             */
            /**
             * @function init
             */
            $scope.init = function() {
                //On load screen logic
                var requestData = {};
                /*|button_mapping|onbeforesend|6ABBBE97-B224-5329-70E9-0A50ADC4A0A5||1500|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("getMenu1_service")(requestData).then(
                    /*|service_bookmark|bookmark|6ABBBE97-B224-5329-70E9-0A50ADC4A0A5||7690|*/
                    function(success) { // success callback
                        (function mapping8022(success, $scope) {
                            var tempmenu1_scope = $scope.tempmenu1;
                            tempmenu1_scope = success.data;
                            $scope.tempmenu1 = tempmenu1_scope;
                            /*|button_mapping|onsuccess|6ABBBE97-B224-5329-70E9-0A50ADC4A0A5||8022|*/
                        })(success, $scope);
                        var myStringArray1 = JSON.stringify($scope.tempmenu1);
                        localStorage.setItem("localStorageStringArray1", myStringArray1); // set the value
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                /*|button_mapping|onbeforesend|BA3E5B94-9D1F-4627-EFBD-71B10AE864D5||9184|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("getMenu2_service")(requestData).then(
                    /*|service_bookmark|bookmark|BA3E5B94-9D1F-4627-EFBD-71B10AE864D5||8166|*/
                    function(success) { // success callback
                        (function mapping7075(success, $scope) {
                            var tempmenu2_scope = $scope.tempmenu2;
                            tempmenu2_scope = success.data;
                            $scope.tempmenu2 = tempmenu2_scope;
                            /*|button_mapping|onsuccess|BA3E5B94-9D1F-4627-EFBD-71B10AE864D5||7075|*/
                        })(success, $scope);
                        var myStringArray2 = JSON.stringify($scope.tempmenu2);
                        localStorage.setItem("localStorageStringArray2", myStringArray2); // set the value
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                /*|button_mapping|onbeforesend|3AFF7E68-470E-B4E4-3CFE-4C1862E2897C||9521|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("getMenu3_service")(requestData).then(
                    /*|service_bookmark|bookmark|3AFF7E68-470E-B4E4-3CFE-4C1862E2897C||9773|*/
                    function(success) { // success callback
                        (function mapping5631(success, $scope) {
                            var tempmenu3_scope = $scope.tempmenu3;
                            tempmenu3_scope = success.data;
                            $scope.tempmenu3 = tempmenu3_scope;
                            /*|button_mapping|onsuccess|3AFF7E68-470E-B4E4-3CFE-4C1862E2897C||5631|*/
                        })(success, $scope);
                        var myStringArray3 = JSON.stringify($scope.tempmenu3);
                        localStorage.setItem("localStorageStringArray3", myStringArray3); // set the value
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                /*|button_mapping|onbeforesend|A4877193-B9D8-B138-9BCF-4B3937B1FDE1||4001|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("getMenu4_service")(requestData).then(
                    /*|service_bookmark|bookmark|A4877193-B9D8-B138-9BCF-4B3937B1FDE1||8330|*/
                    function(success) { // success callback
                        (function mapping3047(success, $scope) {
                            var tempmenu4_scope = $scope.tempmenu4;
                            tempmenu4_scope = success.data;
                            $scope.tempmenu4 = tempmenu4_scope;
                            /*|button_mapping|onsuccess|A4877193-B9D8-B138-9BCF-4B3937B1FDE1||3047|*/
                        })(success, $scope);
                        var myStringArray4 = JSON.stringify($scope.tempmenu4);
                        localStorage.setItem("localStorageStringArray4", myStringArray4); // set the value
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                var requestData = {};
                /*|button_mapping|onbeforesend|CDC9E0AB-525D-D7B3-2C94-CAC354B32F2D||9112|*/
                // read more about using rest services: https://links.appery.io/ve-snippet-rest
                Apperyio.get("getMenu5_service")(requestData).then(
                    /*|service_bookmark|bookmark|CDC9E0AB-525D-D7B3-2C94-CAC354B32F2D||7639|*/
                    function(success) { // success callback
                        (function mapping8710(success, $scope) {
                            var tempmenu5_scope = $scope.tempmenu5;
                            tempmenu5_scope = success.data;
                            $scope.tempmenu5 = tempmenu5_scope;
                            /*|button_mapping|onsuccess|CDC9E0AB-525D-D7B3-2C94-CAC354B32F2D||8710|*/
                        })(success, $scope);
                        var myStringArray5 = JSON.stringify($scope.tempmenu5);
                        localStorage.setItem("localStorageStringArray5", myStringArray5); // set the value
                    },
                    function(error) { // callback to handle request error
                    },
                    function(notify) { // notify callback, can fire few times
                    });
                //menu1 Recall
                var myStringArray1 = localStorage.getItem("localStorageStringArray1");
                var currentArray1 = [];
                currentArray1 = JSON.parse(myStringArray1);
                //var myVar = localStorage.getItem(myVar); // get the value
                //console.log("lowermenu", currentArray1)
                //menu2 Recall
                var myStringArray2 = localStorage.getItem("localStorageStringArray2");
                var currentArray2 = [];
                currentArray2 = JSON.parse(myStringArray2);
                //var myVar = localStorage.getItem(myVar); // get the value
                //console.log("lowermenu2", currentArray2)
                //menu3 Recall
                var myStringArray3 = localStorage.getItem("localStorageStringArray3");
                var currentArray3 = [];
                currentArray3 = JSON.parse(myStringArray3);
                //var myVar = localStorage.getItem(myVar); // get the value
                //console.log("lowermenu3", currentArray3)
                //menu4 Recall
                var myStringArray4 = localStorage.getItem("localStorageStringArray4");
                //console.log("lowermenu4a", myStringArray4)
                var currentArray4 = [];
                currentArray4 = JSON.parse(myStringArray4);
                //var myVar = localStorage.getItem(myVar); // get the value
                //console.log("lowermenu4", currentArray4)
                //menu5 Recall
                var myStringArray5 = localStorage.getItem("localStorageStringArray5");
                //console.log("lowermenu4a", myStringArray4)
                var currentArray5 = [];
                currentArray5 = JSON.parse(myStringArray5);
                //var myVar = localStorage.getItem(myVar); // get the value
                //console.log("lowermenu5", currentArray5)
                var pass = {};
                $scope.company = {};
                $scope.type = {};
                $scope.model = {};
                $scope.storage = {};
                $scope.finish = {};
                var allCompanies = currentArray1;
                var allTypes = currentArray2;
                var allModels = currentArray3;
                //new
                var allStorages = currentArray4;
                //new new
                var allFinishes = currentArray5;
                $scope.companies = allCompanies;
                $scope.$watch('company', function() {
                    $scope.types = allTypes.filter(function(s) {
                        return s.CompanyId == $scope.company.Id;
                    });
                    //$scope.city = {};
                    $scope.type = {};
                    $scope.models = [];
                    $scope.storages = [];
                    $scope.finishes = [];
                });
                $scope.$watch('type', function() {
                    $scope.models = allModels.filter(function(c) {
                        return c.TypeId == $scope.type.Id;
                    });
                    $scope.city = {};
                });
                $scope.$watch('model', function() {
                    $scope.storages = allStorages.filter(function(c) {
                        return c.ModelId == $scope.model.Id;
                    });
                    // Check to see if its a Cellular ipad
                    if ($scope.type.TypeName == "iPad - WiFi/Cellular") {
                        $scope.model.ModelName = $scope.model.ModelName + " - Cellular";
                    } else {
                        $scope.model.ModelName = $scope.model.ModelName;
                    }
                    $scope.storage = {};
                });
                //new
                $scope.$watch('storage', function() {
                    $scope.finishes = allFinishes.filter(function(c) {
                        return c.StorageId == $scope.storage.Id;
                    });
                    $scope.finish = {};
                });
            };
            /**
             * @function MakeData
             */
            $scope.MakeData = function() {
                //Get User
                var userData = Apperyio.get("dataStorage");
                var AllData = userData.current;
                var buyer = AllData.username;
                var session = AllData.session
                var bMail = AllData.email
                var bCell = AllData.MobilePhone
                var token = AllData.session;
                //Get User     
                console.log(token);
                RequestManu = ($scope.company.CompanyName);
                RequestType = ($scope.type.TypeName);
                RequestModel = ($scope.model.ModelName);
                RequestMem = ($scope.storage.StorageName);
                RequestColor = ($scope.finish.FinishName);
                RequestCarrier = ($scope.Carrier);
                RequestKitted = ($scope.Kitted);
                RequestQuan = ($scope.Quantity);
                RequestExpiration = ($scope.Expiration);
                RequestShipping = ($scope.Shipping);
                RequestNotes = ($scope.Notes);
                console.log($scope.finish.FinishName);
                if ($scope.finish.FinishName === undefined) {
                    alert('Please Choose a Color');
                    Apperyio.navigateTo("Buyer_MakeRequest", {});
                } else {
                    // Button Press
                    var requestData = {};
                    requestData = (function mapping4338($scope) {
                        var requestData = {};
                        requestData.params = {};
                        var buyer_scope = buyer;
                        var RequestManu_scope = RequestManu;
                        var RequestModel_scope = RequestModel;
                        var RequestMem_scope = RequestMem;
                        var RequestColor_scope = RequestColor;
                        var bMail_scope = $scope.bMail;
                        var bCell_scope = $scope.bCell;
                        var carrier_scope = $scope.Carrier;
                        var kitted_scope = $scope.Kitted;
                        var Quantity_scope = $scope.Quantity;
                        var Expiratiom_scope = $scope.Expiration;
                        var Shipping_scope = $scope.Shipping;
                        var Notes_scope = $scope.Notes;
                        requestData.params.Buyer_username = buyer_scope;
                        requestData.params.manufacturer = RequestManu_scope;
                        requestData.params.Product = RequestModel_scope;
                        requestData.params.Memory = RequestMem_scope;
                        requestData.params.Color = RequestColor_scope;
                        requestData.params.B_Requests1 = bMail;
                        requestData.params.B_Requests2 = bCell;
                        requestData.params.Carrier = RequestCarrier;
                        requestData.params.Kitted = RequestKitted;
                        requestData.params.Quantity = RequestQuan;
                        requestData.params.Expiration = RequestExpiration;
                        requestData.params.Shipping = RequestShipping;
                        requestData.params.RNotes = RequestNotes;
                        requestData.headers = {};
                        var token_scope = $scope.token;
                        requestData.headers['X-Appery-Session-Token'] = token;
                        console.log("token", token);
                        console.log("Finish", RequestColor_scope);
                        return requestData;
                        /*|button_mapping|onbeforesend|139F3B73-66FE-AFE3-C4CB-F974C80270D0||4338|*/
                    })($scope);
                    // read more about using rest services: https://links.appery.io/ve-snippet-rest
                    Apperyio.get("InsertRequest_service")(requestData).then(
                        /*|service_bookmark|bookmark|139F3B73-66FE-AFE3-C4CB-F974C80270D0||8149|*/
                        function(success) { // success callback
                            /*|button_mapping|onsuccess|139F3B73-66FE-AFE3-C4CB-F974C80270D0||1667|*/
                            var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                                animation: 'slide-in-up', // The animation to show & hide with
                                focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                                backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                                hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                            };
                            Apperyio.get('Modals').loadModal("Modal_Buyer_Request").then(
                                function(modalInstance) {
                                    modalInstance.open(modalOptions).then(function(modal) {
                                        modal.scope.modal = modal;
                                        modal.scope.result = "You have requested the following:";
                                        modal.scope.result1 = RequestManu;
                                        modal.scope.result2 = RequestModel;
                                        modal.scope.result3 = RequestMem;
                                        modal.scope.result4 = RequestColor;
                                        modal.scope.result5 = RequestKitted;
                                        modal.scope.result6 = RequestQuan;
                                        modal.scope.result7 = RequestExpiration;
                                        modal.scope.result8 = RequestShipping;
                                        modal.scope.result9 = RequestCarrier;
                                        modal.show();
                                    });
                                },
                                function(error) {
                                    var modalOptions = { // About Ionic Modal: https://links.appery.io/ve-snippet-modal-ionic
                                        animation: 'slide-in-up', // The animation to show & hide with
                                        focusFirstInput: false, // Whether to autofocus the first input of the modal when shown
                                        backdropClickToClose: true, // Whether to close the modal on clicking the backdrop
                                        hardwareBackButtonClose: true // Whether the modal can be closed using the hardware back button on Android and similar devices
                                    };
                                    Apperyio.get('Modals').loadModal("Info").then(
                                        function(modalInstance) {
                                            modalInstance.open(modalOptions).then(function(modal) {
                                                modal.scope.modal = modal;
                                                modal.scope.result = "Please Try Again. There was an error";
                                                modal.show();
                                            });
                                        },
                                        function(error) {
                                            console.log(error);
                                        });
                                    console.log(error);
                                });
                        },
                        function(error) { // callback to handle request error
                        },
                        function(notify) { // notify callback, can fire few times
                        });
                    Apperyio.navigateTo("Buyer_Home", {});
                }
            };
        }
    });